
AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/*
    - db/schema.rb
    - db/*.rb
    - vendor/**/*
    - node_modules/**/*

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 50

Metrics/MethodLength:
  Max: 50

Lint/MissingSuper:
  Enabled: false
